import type { Annotation, AnnotationType } from './types'
import { calculateSegmentGradients } from './effort'

/**
 * Generate a unique ID for a new annotation.
 */
export function generateAnnotationId(_type: AnnotationType): string {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID()
  }
  return `ann_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`
}

/**
 * Detect the highest elevation point (summit).
 * Always returns a result for non-empty data.
 */
function detectSummit(data: Array<{ label: string; value: number }>): Annotation {
  let maxIdx = 0
  let maxVal = data[0].value
  for (let i = 1; i < data.length; i++) {
    if (data[i].value > maxVal) {
      maxVal = data[i].value
      maxIdx = i
    }
  }
  const progress = Math.max(0.01, Math.min(0.99, maxIdx / (data.length - 1)))
  return {
    id: `auto_summit`,
    progress,
    text: `Gipfel ${Math.round(maxVal)}m`,
    enabled: true,
    type: 'summit',
    isAutoGenerated: true,
  }
}

/**
 * Detect the steepest sustained climb.
 * Returns null if the route is too flat (no climbing segment above threshold).
 */
function detectSteepestClimb(data: Array<{ label: string; value: number }>): Annotation | null {
  const gradients = calculateSegmentGradients(data)
  // Only consider climbing segments (gradient > 0.5 means uphill in normalized scale)
  const hasSignificantClimb = gradients.some(g => g > 0.6)
  if (!hasSignificantClimb) return null

  const windowSize = Math.max(3, Math.floor(data.length * 0.03))
  let bestAvg = -Infinity
  let bestCenter = 0

  for (let i = 0; i <= gradients.length - windowSize; i++) {
    let sum = 0
    for (let j = i; j < i + windowSize; j++) {
      sum += gradients[j]
    }
    const avg = sum / windowSize
    if (avg > bestAvg) {
      bestAvg = avg
      bestCenter = i + Math.floor(windowSize / 2)
    }
  }

  const progress = Math.max(0.01, Math.min(0.99, bestCenter / (data.length - 1)))
  return {
    id: `auto_steepest_climb`,
    progress,
    text: 'Steilster Anstieg',
    enabled: true,
    type: 'steepest_climb',
    isAutoGenerated: true,
  }
}

/**
 * Detect the steepest sustained descent.
 * Returns null if no significant descent exists.
 */
function detectSteepestDescent(data: Array<{ label: string; value: number }>): Annotation | null {
  const gradients = calculateSegmentGradients(data)
  const hasSignificantDescent = gradients.some(g => g < 0.4)
  if (!hasSignificantDescent) return null

  const windowSize = Math.max(3, Math.floor(data.length * 0.03))
  let bestAvg = Infinity
  let bestCenter = 0

  for (let i = 0; i <= gradients.length - windowSize; i++) {
    let sum = 0
    for (let j = i; j < i + windowSize; j++) {
      sum += gradients[j]
    }
    const avg = sum / windowSize
    if (avg < bestAvg) {
      bestAvg = avg
      bestCenter = i + Math.floor(windowSize / 2)
    }
  }

  const progress = Math.max(0.01, Math.min(0.99, bestCenter / (data.length - 1)))
  return {
    id: `auto_steepest_descent`,
    progress,
    text: 'Steilstes Gefälle',
    enabled: true,
    type: 'steepest_descent',
    isAutoGenerated: true,
  }
}

/**
 * Detect the longest continuous descent.
 * Returns null if no significant descent run exists (< 5% of total points).
 */
function detectLongestDescent(data: Array<{ label: string; value: number }>): Annotation | null {
  const minRunLength = Math.max(3, Math.floor(data.length * 0.05))

  let bestStart = -1
  let bestEnd = -1
  let bestLength = 0
  let runStart = -1

  for (let i = 1; i < data.length; i++) {
    if (data[i].value < data[i - 1].value) {
      if (runStart === -1) runStart = i - 1
    } else {
      if (runStart !== -1) {
        const runLength = i - runStart
        if (runLength > bestLength) {
          bestLength = runLength
          bestStart = runStart
          bestEnd = i - 1
        }
        runStart = -1
      }
    }
  }
  // Check final run
  if (runStart !== -1) {
    const runLength = data.length - 1 - runStart
    if (runLength > bestLength) {
      bestLength = runLength
      bestStart = runStart
      bestEnd = data.length - 1
    }
  }

  if (bestLength < minRunLength) return null

  const midIdx = Math.round((bestStart + bestEnd) / 2)
  const progress = Math.max(0.01, Math.min(0.99, midIdx / (data.length - 1)))
  return {
    id: `auto_longest_descent`,
    progress,
    text: 'Längster Abstieg',
    enabled: true,
    type: 'longest_descent',
    isAutoGenerated: true,
  }
}

/**
 * Enforce a minimum gap between annotations to prevent overlap.
 * Annotations that would overlap are nudged forward; if nudging pushes past 0.99,
 * the annotation is dropped.
 */
function deduplicateAnnotations(annotations: Annotation[], minGap: number): Annotation[] {
  if (annotations.length === 0) return []

  const sorted = [...annotations].sort((a, b) => a.progress - b.progress)
  const result: Annotation[] = [sorted[0]]

  for (let i = 1; i < sorted.length; i++) {
    const prev = result[result.length - 1]
    const curr = sorted[i]
    if (curr.progress - prev.progress < minGap) {
      const nudged = prev.progress + minGap
      if (nudged > 0.99) continue  // Drop — no room
      result.push({ ...curr, progress: nudged })
    } else {
      result.push(curr)
    }
  }

  return result
}

/**
 * Auto-detect interesting moments in elevation data.
 * Returns up to 4 annotations: summit, steepest climb, steepest descent, longest descent.
 */
export function detectAnnotations(
  data: Array<{ label: string; value: number }>
): Annotation[] {
  if (data.length < 5) return []

  const candidates: (Annotation | null)[] = [
    detectSummit(data),
    detectSteepestClimb(data),
    detectSteepestDescent(data),
    detectLongestDescent(data),
  ]

  const valid = candidates.filter((a): a is Annotation => a !== null)
  return deduplicateAnnotations(valid, 0.05)
}
