import { describe, it, expect } from 'vitest'
import { detectAnnotations, generateAnnotationId } from './annotationDetection'

// ── helpers ───────────────────────────────────────────────────────────────────

function makeData(values: number[]) {
  return values.map((v, i) => ({ label: String(i), value: v }))
}

/** A route that climbs steeply, stays flat, then descends long */
function mountainRoute(length = 100) {
  return makeData([
    ...Array.from({ length: 30 }, (_, i) => 200 + i * 20),   // steep climb 200→800
    ...Array.from({ length: 20 }, () => 800),                  // plateau
    ...Array.from({ length: 50 }, (_, i) => 800 - i * 10),    // long descent 800→300
  ])
}

// ── generateAnnotationId ──────────────────────────────────────────────────────

describe('generateAnnotationId', () => {
  it('returns a non-empty string', () => {
    const id = generateAnnotationId('summit')
    expect(typeof id).toBe('string')
    expect(id.length).toBeGreaterThan(0)
  })

  it('returns unique ids on successive calls', () => {
    const ids = new Set(Array.from({ length: 20 }, () => generateAnnotationId('summit')))
    expect(ids.size).toBe(20)
  })
})

// ── detectAnnotations ─────────────────────────────────────────────────────────

describe('detectAnnotations', () => {
  it('returns empty array for fewer than 5 points', () => {
    expect(detectAnnotations([])).toEqual([])
    expect(detectAnnotations(makeData([100, 200, 300]))).toEqual([])
    expect(detectAnnotations(makeData([100, 200, 300, 400]))).toEqual([])
  })

  it('returns at least a summit annotation for non-flat data', () => {
    const data = mountainRoute()
    const annotations = detectAnnotations(data)
    expect(annotations.length).toBeGreaterThan(0)
    const summit = annotations.find(a => a.type === 'summit')
    expect(summit).toBeDefined()
  })

  it('summit progress is between 0.01 and 0.99', () => {
    const data = mountainRoute()
    const summit = detectAnnotations(data).find(a => a.type === 'summit')!
    expect(summit.progress).toBeGreaterThanOrEqual(0.01)
    expect(summit.progress).toBeLessThanOrEqual(0.99)
  })

  it('summit is near the highest point', () => {
    // Peak is at index 49 (end of climb), out of 100 points → progress ~0.49
    const data = mountainRoute(100)
    const summit = detectAnnotations(data).find(a => a.type === 'summit')!
    expect(summit.progress).toBeGreaterThan(0.2)
    expect(summit.progress).toBeLessThan(0.6)
  })

  it('all returned annotations have required fields', () => {
    const data = mountainRoute()
    for (const ann of detectAnnotations(data)) {
      expect(ann).toHaveProperty('id')
      expect(ann).toHaveProperty('progress')
      expect(ann).toHaveProperty('text')
      expect(ann).toHaveProperty('enabled', true)
      expect(ann).toHaveProperty('type')
      expect(ann).toHaveProperty('isAutoGenerated', true)
    }
  })

  it('annotations have minimum gap of 0.05 between each other', () => {
    const data = mountainRoute(200)
    const annotations = detectAnnotations(data)
    const sorted = [...annotations].sort((a, b) => a.progress - b.progress)
    for (let i = 1; i < sorted.length; i++) {
      expect(sorted[i].progress - sorted[i - 1].progress).toBeGreaterThanOrEqual(0.05 - 0.001)
    }
  })

  it('returns at most 4 annotations', () => {
    const data = mountainRoute(200)
    expect(detectAnnotations(data).length).toBeLessThanOrEqual(4)
  })

  it('flat route (no climb/descent) only has summit annotation', () => {
    const flat = makeData(Array.from({ length: 50 }, () => 500))
    const annotations = detectAnnotations(flat)
    // Only summit is guaranteed; no steepest climb/descent on flat
    const types = annotations.map(a => a.type)
    expect(types).not.toContain('steepest_climb')
    expect(types).not.toContain('steepest_descent')
  })

  it('summit text includes elevation in meters', () => {
    const data = mountainRoute()
    const summit = detectAnnotations(data).find(a => a.type === 'summit')!
    expect(summit.text).toMatch(/\d+m/)
  })
})
